### ISSUE TITLE
Improve video tracker

### ISSUE THREAD

**Issue by HonzaMikula** [CardinalPath/gas#22]
It is possible to add new state events for video? There is possibilities of -1 (unstarted), 0 (ended), 1 (playing), 2 (paused), 3 (buffering),5 (video cued) (https://developers.google.com/youtube/iframe_api_reference#Events)

It would be also good if there was difference between starting video (first time of event playing) and playing (other time - after pausing, rewind,..)

Thanks.

**Comment by eduardocereto** [comment]
For youtube we only use ended, playing and paused. The reason behind it is because there were never good use cases for the other events. GAS goal is not be a data puke library. We want to enforce best practices as well. 

That said I'd like to hear some real use cases on other events. We could add the other events as options not enabled by default just like the video played percentages. 

I like the idea of differentiating playing and re-playing events, even though I think it could be a little too much.
