### ISSUE TITLE
Youtube Video: Use iframe_api instead of player_api ?

### ISSUE THREAD

**Issue by googleanalyticsresoneo** [CardinalPath/gas#31]
Hi

Since this plugin only handles Video players inserted through iframes, shouldn't it load www.youtube.com/iframe_api instead of www.youtube.com/player_api ??

https://developers.google.com/youtube/iframe_api_reference
https://developers.google.com/youtube/getting_started#player_apis

**Comment by eduardocereto** [comment]
Seems like both are the same. I think they renamed it on July 19 per Release docs:

https://developers.google.com/youtube/iframe_api_reference

Still I probably should update. I'll try to update and do a realease later this week. The youtube is still broken on the production version due to the changes on youtube that are already fixed on the master branch.

**Comment by tomfuertes** [comment]
Is this the issue pending a fix in 1.11.1?

**Comment by tomfuertes** [comment]
Pretty sure this was fixed in the 1.10.1 release
