### ISSUE TITLE
Surpress pushes to _gasTrack* from hitting _gaq 

### ISSUE THREAD

**Issue by tomfuertes** [CardinalPath/gas#39]
Feels so dirty getting these error messages all over my console :(

```
_gaq.push processing "_gasMultiDomain" for args: "[mousedown]":  ga_debug.js:18
> Called method "_gasMultiDomain" threw exception.TypeError: Cannot call method 'apply' of undefined ga_debug.js:18
_gaq.push processing "_gasTrackOutboundLinks" for args: "[]":  ga_debug.js:18
> Called method "_gasTrackOutboundLinks" threw exception.TypeError: Cannot call method 'apply' of undefined 
```

Thoughts?

**Comment by eduardocereto** [comment]
I pushed my functions inside _gaq in case that function suddenly became available on _gaq and because if you push something that is unknown there it is usually ignored. Now I prefix everything with _gas so there's no possibility that my function will have a clash with an inside function. 

This exception seems to only pop-up if you use ga-debug.js so very minor issue
