### ISSUE TITLE
Still no luck with in-page analytics

### ISSUE THREAD

**Issue by vossavant** [CardinalPath/gas#54]
This is a follow up to https://github.com/CardinalPath/gas/issues/52 and https://github.com/CardinalPath/gas/issues/53.

After making the changes suggested in #53, the errors disappeared from the console, but we still get the error screen in Analytics (see screenshot in #52).

At this point it appears we will have to consider dropping GAS, but before doing so I wanted to check if we will lose any of our Analytics history if we switch from GAS to regular GA. Can you comment on this? Thanks for your help on this issue.

**Comment by tomfuertes** [comment]
If you read the error you're getting from google in #52 it just says the scraper can't find a reference to ga.js in the &lt;/head&gt;. This is intentional for the way GAS loads and shouldn't affect anything.  See my comment here again: https://github.com/CardinalPath/gas/issues/52#issuecomment-26805558

You will lose all auto tracking enabled by the following GAS apis:

``` javascript
       _gas.push(['_gasTrackForms']);
       _gas.push(['_gasTrackOutboundLinks']);
       _gas.push(['_gasTrackMaxScroll']);
       _gas.push(['_gasTrackDownloads']);
       _gas.push(['_gasTrackMailto']);
```

You're profile still collecting data w/ GAS right? Seems like your best course of action is to ignore the Google Error. Let me know if I'm missing something. Happy to close a bug report if you can nail it down to something other than the auto scraper giving you an expected error.
